M48
; DRILL file {KiCad (7.0.0-0)} date Friday, 31 March 2023 at 02:52:23 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-31T14:52:23+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1299
%
G90
G05
T1
X4.0339Y-3.4307
T2
X4.0339Y-2.6433
T3
X3.9339Y-2.339
X3.9339Y-3.739
X5.3339Y-2.339
X5.3339Y-3.739
T0
M30
